#' Local indicators of spatial connectivity
#'
#' Computes integrated activation, merging, and net local contributions and
#' assesses local merging using conditional random relabeling with the focal
#' value held fixed.
#'
#' @param x Numeric vector with one value per areal unit.
#' @param graph Spatial adjacency information. Accepted formats are an
#'   `spdep` `nb` object, an `spdep` `listw` object, a two-column edge list,
#'   or an `n x n` adjacency matrix.
#' @param reference Reference level used to center `x`. Either a finite numeric
#'   value or one of `"mean"`, `"median"`, or `"zero"`.
#' @param scale Positive scale used for the deviations. Either a finite numeric
#'   value or one of `"sd"`, `"mad"`, or `"none"`.
#' @param side Analysis direction: `"superlevel"`, `"sublevel"`, or `"both"`.
#' @param n_perm Number of conditional random relabelings for each focal area.
#' @param seed Optional random seed for the conditional relabelings.
#' @param adjust Multiple-testing adjustment method passed to
#'   [stats::p.adjust()]. Use `"none"` for no adjustment.
#' @param alpha Significance level used for the optional profile classification.
#' @param activation_tail Upper-tail proportion of the selected data vector used
#'   to define high activation. The case study uses `0.15`.
#' @param significance Which inferential value defines connector profiles:
#'   `"unadjusted"` or `"adjusted"`.
#' @param classify Logical; if `TRUE`, return core, bridge, and peak/trough
#'   connector profiles.
#' @param progress Logical; display a text progress bar.
#' @param keep_permutations Logical; if `TRUE`, retain the matrix of conditional
#'   relabeling values of the local merging indicator.
#'
#' @details
#' At each activation event, an entering area may touch one or more previously
#' active connected components. Each such component creates one merging unit.
#' One half of the unit is assigned to the entering area and the remaining half
#' is divided equally among its neighbours belonging to that component. The
#' normalization is therefore component-specific.
#'
#' The integrated merging contribution `M_i` is the local indicator of spatial
#' connectivity. Large `M_i` values indicate strong cumulative participation in
#' the fusions through which superlevel regions become connected. Applying the
#' same construction to the sign-reversed data gives the corresponding sublevel
#' interpretation for low-valued regions.
#'
#' Conditional inference fixes the focal selected value `y_i` and randomly
#' relabels all remaining values. Because `A_i` is fixed in this construction,
#' an upper-tail test for `M_i` is exactly equivalent to a lower-tail test for
#' `L_i = A_i - M_i`.
#'
#' The current exact local allocation assumes that the positive values of the
#' selected vector are distinct, so areas enter one at a time. Exact positive
#' ties trigger an informative error. This is separate from the structural edge
#' ties generated by adjacency, which require no tie-breaking under the current
#' component-specific allocation.
#'
#' @return For one side, an object of class `spatconnect_local`. Its `results`
#'   component contains `A`, `M`, `L`, conditional null summaries for `M`,
#'   unadjusted and adjusted p-values, and the optional connectivity profile.
#'   For `side = "both"`, an object containing `superlevel` and `sublevel`
#'   analyses is returned.
#' @export
#'
#' @examples
#' x <- c(3, 2, 1, -1)
#' edges <- data.frame(i = c(1, 2, 3), j = c(2, 3, 4))
#' local_connectivity(x, edges, reference = 0, scale = "none",
#'                    side = "superlevel", n_perm = 99, seed = 1,
#'                    progress = FALSE)
local_connectivity <- function(
    x,
    graph,
    reference = "mean",
    scale = "sd",
    side = c("both", "superlevel", "sublevel"),
    n_perm = 999,
    seed = NULL,
    adjust = "BH",
    alpha = 0.05,
    activation_tail = 0.15,
    significance = c("unadjusted", "adjusted"),
    classify = TRUE,
    progress = interactive(),
    keep_permutations = FALSE
) {
  side <- match.arg(side)
  significance <- match.arg(significance)

  if (length(n_perm) != 1L || !is.finite(n_perm) || n_perm < 1 || n_perm != floor(n_perm)) {
    stop("`n_perm` must be a positive integer.", call. = FALSE)
  }
  n_perm <- as.integer(n_perm)

  if (length(alpha) != 1L || !is.finite(alpha) || alpha <= 0 || alpha >= 1) {
    stop("`alpha` must lie strictly between 0 and 1.", call. = FALSE)
  }
  if (length(activation_tail) != 1L || !is.finite(activation_tail) ||
      activation_tail <= 0 || activation_tail >= 0.5) {
    stop("`activation_tail` must lie strictly between 0 and 0.5.", call. = FALSE)
  }

  prep <- .prepare_signal(x, reference = reference, scale = scale)
  edges <- .as_edge_list(graph, length(x))
  adj <- .adjacency_list(length(x), edges)
  ids <- .area_ids(x, graph)

  run_one <- function(which_side) {
    y <- .side_vector(prep$z, which_side)
    .local_connectivity_one(
      y = y,
      x = prep$x,
      z = prep$z,
      area_id = ids,
      edges = edges,
      adj = adj,
      side = which_side,
      reference = prep$reference,
      scale = prep$scale,
      n_perm = n_perm,
      seed = seed,
      adjust = adjust,
      alpha = alpha,
      activation_tail = activation_tail,
      significance = significance,
      classify = classify,
      progress = progress,
      keep_permutations = keep_permutations
    )
  }

  if (side == "both") {
    out <- list(
      superlevel = run_one("superlevel"),
      sublevel = run_one("sublevel"),
      reference = prep$reference,
      scale = prep$scale,
      n_areas = length(x),
      n_edges = nrow(edges)
    )
    class(out) <- "spatconnect_local_both"
    return(out)
  }

  run_one(side)
}

.local_connectivity_one <- function(
    y, x, z, area_id, edges, adj, side, reference, scale,
    n_perm, seed, adjust, alpha, activation_tail, significance,
    classify, progress, keep_permutations
) {
  if (!is.null(seed)) set.seed(seed)

  n <- length(y)
  obs <- .integrated_aml(y, edges, adj = adj)

  null_mean <- numeric(n)
  null_sd <- numeric(n)
  p_value <- numeric(n)
  perm_store <- if (isTRUE(keep_permutations)) {
    matrix(NA_real_, nrow = n, ncol = n_perm)
  } else {
    NULL
  }

  if (isTRUE(progress)) {
    pb <- utils::txtProgressBar(min = 0, max = n * n_perm, style = 3)
    counter <- 0L
    on.exit(close(pb), add = TRUE)
  }

  all_idx <- seq_len(n)

  for (i in all_idx) {
    others <- all_idx[all_idx != i]
    vals <- numeric(n_perm)

    for (r in seq_len(n_perm)) {
      y_r <- y
      y_r[others] <- sample(y[others], size = length(others), replace = FALSE)

      # Recompute the complete component-specific local decomposition after
      # every conditional relabeling, matching the procedure used in the paper.
      vals[r] <- .integrated_aml(y_r, edges, adj = adj)$M[i]

      if (isTRUE(progress)) {
        counter <- counter + 1L
        utils::setTxtProgressBar(pb, counter)
      }
    }

    null_mean[i] <- mean(vals)
    null_sd[i] <- stats::sd(vals)
    p_value[i] <- (1 + sum(vals >= obs$M[i])) / (n_perm + 1)

    if (isTRUE(keep_permutations)) perm_store[i, ] <- vals
  }

  p_adjusted <- if (identical(adjust, "none")) {
    p_value
  } else {
    stats::p.adjust(p_value, method = adjust)
  }

  excess <- obs$M - null_mean
  z_score <- excess / null_sd
  z_score[!is.finite(z_score)] <- NA_real_

  activation_cutoff <- max(
    0,
    as.numeric(stats::quantile(
      y,
      probs = 1 - activation_tail,
      names = FALSE,
      type = 7
    ))
  )

  profile <- rep(NA_character_, n)
  if (isTRUE(classify)) {
    p_for_class <- if (significance == "adjusted") p_adjusted else p_value
    profile <- .connectivity_profile(
      y = y,
      L = obs$L,
      p = p_for_class,
      cutoff = activation_cutoff,
      alpha = alpha,
      side = side
    )
  }

  results <- data.frame(
    area_id = area_id,
    x = x,
    z = z,
    y = y,
    A = obs$A,
    M = obs$M,
    L = obs$L,
    q_entry = obs$q_entry,
    M_null_mean = null_mean,
    M_null_sd = null_sd,
    M_excess = excess,
    M_z_score = z_score,
    p_value = p_value,
    p_adjusted = p_adjusted,
    profile = profile,
    stringsAsFactors = FALSE
  )

  out <- list(
    side = side,
    n_areas = n,
    n_edges = nrow(edges),
    reference = reference,
    scale = scale,
    n_perm = n_perm,
    adjust = adjust,
    alpha = alpha,
    activation_tail = activation_tail,
    activation_cutoff = activation_cutoff,
    significance = significance,
    results = results,
    integrated_B = obs$B,
    allocation_rule = obs$allocation_rule
  )

  if (isTRUE(keep_permutations)) out$M_relabelings <- perm_store

  class(out) <- "spatconnect_local"
  out
}

.connectivity_profile <- function(y, L, p, cutoff, alpha, side) {
  active <- y > 0
  high <- active & y >= cutoff
  significant <- is.finite(p) & p < alpha

  out <- rep("Not significant", length(y))
  out[active & !high & significant] <- "Bridge connector"
  out[high & significant & L <= 0] <- "Core connector"

  tail_label <- if (side == "superlevel") "Peak connector" else "Trough connector"
  out[high & significant & L > 0] <- tail_label

  factor(
    out,
    levels = c("Core connector", "Bridge connector", tail_label, "Not significant")
  )
}
